services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_network
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/backend/data
    ports:
      - "1323:1323"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge