services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_network
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/backend/data
    ports:
      - "1323:1323"
    networks:
      - app_network

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - app_network

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
      - selenium
    networks:
      - app_network

networks:
  app_network:
    driver: bridge