services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    networks:
      - app_network

networks:
  app_network