services:
  controller-app:
    build: .
    ports:
      - "9000:9000"
    restart: always

  ngrok:
      image: ngrok/ngrok
      depends_on:
        - controller-app
      environment:
        NGROK_AUTHTOKEN: ${NGROK_TOKEN}
      ports:
        - "4040:4040"
      command: http controller-app:9000